---
# task file for linux-updates

- import_tasks: linux-updates-centos-redhat.yml
  when: ansible_distribution=="CentOS" or ansible_distribution=="RedHat"

- import_tasks: linux-updates-debian-ubuntu.yml
  when: ansible_distribution=="Ubuntu" or ansible_distribution=="Debian"
