---
  ###
  ###
  # SETUP DOCKER COMPOSE
  ###
  - name: Install Python 3 PIP
    apt:
      name:
      - python3-pip
      state: latest
      update_cache: yes
      autoclean: yes

  - name: Update PIP
    pip: 
      name: pip
      state: latest

  - name: Install docker-compose
    pip: 
      name: docker-compose
      state: latest

  - name: Get Docker Compose version
    shell: docker-compose --version
    register: docker_compose_version

  - name: Show Docker Compose version
    debug: msg="{{ docker_compose_version.stdout_lines }}"
