---
  ###
  ###
  # SETUP DOCKER USER
  ###
  - name: Create user {{ docker_user }} to manage Docker
    user:
      name: "{{ docker_user }}"
      append: yes
      comment: Docker User
      groups: docker
      password: "{{ docker_password }}"
      expires: -1
      home: /home/{{ docker_user }}
      shell: /bin/bash
      state: present

  - name: Get User info
    shell: passwd -S {{ docker_user }}
    register: docker_user

  - name: Show User info
    debug: msg="{{ docker_user.stdout_lines }}"
