---
  ###
  ###
  # SETUP DOCKER FOR Debian: https://docs.docker.com/engine/install/debian/
  ###
  ###
  - name: Uninstall old versions of Docker
    apt:
      name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      state: absent
      autoclean: yes

  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: latest
      update_cache: yes
      autoclean: yes

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker's stable Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
      state: present
      filename: "docker"

  - name: Install Docker Engine
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: yes
      autoclean: yes

  - name: Enable and Start Docker service
    systemd:
      state: started
      name: docker
      enabled: yes

  - name: Configure Docker /etc/docker/daemon.json
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Restart Docker service
    systemd:
      state: restarted
      name: docker
      enabled: yes

  - name: Get Docker version
    shell: docker --version
    register: docker_version

  - name: Show Docker version
    debug: msg="{{ docker_version.stdout_lines }}"
