---
# defaults file for linux-docker

# Docker Logs Settings
docker_logs_max_size: 10m
docker_logs_max_file: 3

# Docker Registries Settings
# Example of NO registries: []
# Example of multiple registries: ["reg1.example.com:5000", "reg2.example.com:5000"]
docker_registry_mirrors: []
docker_insecure_registries: []

# Docker User Settings
docker_create_user: false
docker_user: <user>
docker_password: '*'

# Docker Compose Setting
docker_compose_setup: false
